apiVersion: v1
entries:
  svc1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-04-12T10:33:53.112888+02:00"
    description: A Helm chart for Kubernetes
    digest: db81de61799a628e30293359617ec68183da53ebcbf2c6575adc22ce03df9639
    name: svc1
    type: application
    urls:
    - https://github.com/gsamr/helm/tree/main/charts/svc1-0.1.0.tgz
    version: 0.1.0
  svc2:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-04-12T10:33:53.113066+02:00"
    description: A Helm chart for Kubernetes
    digest: d6de3eb533be974213ef7ae0411b2373b61aec0a2ddd5ea897172c28fc452565
    name: svc2
    type: application
    urls:
    - https://github.com/gsamr/helm/tree/main/charts/svc2-0.1.0.tgz
    version: 0.1.0
generated: "2024-04-12T10:33:53.112165+02:00"
